name: cdk-github-actions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.16
        uses: actions/setup-node@v1
        with:
          node-version: 20.16

      - name: Setup dependencies
        run: npm ci
        working-directory: infra/CDK

      - name: Build
        run: npm run build
        working-directory: infra/CDK

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: npm run cdk -- --app="./bin/cdk.js" deploy StaticSiteStack
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: infra/CDK